// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Country struct {
	Country     string  `json:"country" db:"country_id"`
	Probability float64 `json:"probability" db:"probability"`
}

type NewPerson struct {
	Name       string `json:"name"`
	Surname    string `json:"surname"`
	Patronymic string `json:"patronymic"`
}

type Person struct {
	ID         string `json:"id" db:"id"`
	Name       string `json:"name" db:"p_name"`
	Surname    string `json:"surname" db:"surname"`
	Patronymic string `json:"patronymic" db:"patronymic"`
	Age        int    `json:"age" db:"age"`
	Gender     string `json:"gender" db:"gender"`
}
